#Este fichero es vital para que cierto programa (coolify) pueda entender el proyecto
#Aunque este proyecto lo desplegar√© en Netlify
[phases.setup]
nixPkgs= ["bun"]

[phases.install]
cmds= ["bum install"]

[phases.build]
cmds= []

[start]
cmd= "bun run start"